In [1]:
import numpy as np

Sigma=np.array([
    [.0625,.0625,.09375],
    [.0625,.2500,.28125],
    [.09375,.28125,.5625]
])

A=np.linalg.cholesky(Sigma)
print(A)
print(A @ A.T)

[[0.25       0.         0.        ]
 [0.25       0.4330127  0.        ]
 [0.375      0.4330127  0.48412292]]
[[0.0625  0.0625  0.09375]
 [0.0625  0.25    0.28125]
 [0.09375 0.28125 0.5625 ]]
